baseURL = "https://www.zeddee.com/"
languageCode = "en-us"
title = "zed tan"
theme = "smol"
publishDir = "docs"

[params] # theme parameters
    author = "zed tan" # author's name
    info = "I write tech things for people." # author's job title or info
    contact = "[zed@shootbird.work](mailto://zed@shootbird.work)"
    description = "zed tan writes tech things for people." # site description
    keywords = "zed, zed tan, technical writer, technical writing, documentation, documentarian, technical documentation, personal, blog" # site keywords
    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = true
    primaryImage = "/images/shootbird_opengraph_blue.png"
    headerImage = "/images/shootbird_opengraph_blue.png"
    googleAnalytics = "UA-129052246-2" # GA tracking ID

# Social links
[[params.social]]
    name = "Email me"
    weight = 6
    url = "mailto:zed@shootbird.work"
# [[params.social]]
#     name = "Blog"
#     weight = 4
#     url = "/posts/"
[[params.social]]
    name = "CV"
    weight = 4
    url = "/cv/"
[[params.social]]
    name = "Shoot Bird"
    weight = 2
    url = "https://shootbird.work"
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/zeddee/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/zeddee/"
[[params.social]]
    name = "Reading List"
    weight = 5
    url = "https://github.com/zeddee/reading-list"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "CV"
    weight = 1
    url = "/cv/"
[[menu.main]]
    name = "Essays"
    weight = 2
    url = "/essays/"
[[menu.main]]
    name = "Tech"
    weight = 2
    url = "/tech-posts/"
[[menu.main]]
    name = "Scratchpad"
    weight = 3
    url = "/scratchpad/"



[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']