baseURL = "https://www.zeddee.com"
languageCode = "en-us"
title = "zed tan"
theme = 'coder'

[params] # theme parameters
    author = "zed tan" # author's name
    info = "documentarian; heuristics." # author's job title or info
    description = "zed tan — documentarian" # site description
    keywords = "zed, zed tan, technical writer, technical writing, documentation, documentarian, technical documentation, personal, blog" # site keywords
    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = true

publishDir = "docs"

# Social links
[[params.social]]
    name = "Blog"
    weight = 4
    url = "/posts/"
[[params.social]]
    name = "Shoot Bird"
    weight = 2
    url = "https://shootbird.work"
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/zeddee/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/zeddee/"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Essays"
    weight = 2
    url = "/essays/"
[[menu.main]]
    name = "Tech"
    weight = 2
    url = "/tech-posts/"
[[menu.main]]
    name = "Scratchpad"
    weight = 3
    url = "/scratchpad/"
